---
bc:
    size: '0x0'
    start: '0x3f450000'
cc:
    size: 0
    start: '0x40220000'
features:
- wifi
- ethernet
fs:
    blocksize: 4096
    cachesize: 512
    page: 256
    progsize: 128
    readsize: 128
    sector: 4096
    size: 7208960
    start: '0x920000'
os:
    heap_end: '0x3ffd4fc4'
    size: '0x1b55f0'
    start: '0x400D0018'
...
